package com.redhat.idaas.eventbuilder.pojos.clinical.hl7;
import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

public class GT1 {
private String GT1_1_SetIDGT1;
private String GT1_2_GuarantorNumber;
private String GT1_3_GuarantorName;
private String GT1_4_GuarantorSpouseName;
private String GT1_5_GuarantorAddress;
private String GT1_6_GuarantorPhNumHome;
private String GT1_7_GuarantorPhNumBusiness;
private String GT1_8_GuarantorDateTimeOfBirth;
private String GT1_9_GuarantorAdministrativeSex;
private String GT1_10_GuarantorType;
private String GT1_11_GuarantorRelationship;
private String GT1_12_GuarantorSSN;
private String GT1_13_GuarantorDateBegin;
private String GT1_14_GuarantorDateEnd;
private String GT1_15_GuarantorPriority;
private String GT1_16_GuarantorEmployerName;
private String GT1_17_GuarantorEmployerAddress;
private String GT1_18_GuarantorEmployerPhoneNumber;
private String GT1_19_GuarantorEmployeeIDNumber;
private String GT1_20_GuarantorEmploymentStatus;
private String GT1_21_GuarantorOrganizationName;
private String GT1_22_GuarantorBillingHoldFlag;
private String GT1_23_GuarantorCreditRatingCode;
private String GT1_24_GuarantorDeathDateAndTime;
private String GT1_25_GuarantorDeathFlag;
private String GT1_26_GuarantorChargeAdjustmentCode;
private String GT1_27_GuarantorHouseholdAnnualIncome;
private String GT1_28_GuarantorHouseholdSize;
private String GT1_29_GuarantorEmployerIDNumber;
private String GT1_30_GuarantorMaritalStatusCode;
private String GT1_31_GuarantorHireEffectiveDate;
private String GT1_32_EmploymentStopDate;
private String GT1_33_LivingDependency;
private String GT1_34_AmbulatoryStatus;
private String GT1_35_Citizenship;
private String GT1_36_PrimaryLanguage;
private String GT1_37_LivingArrangement;
private String GT1_38_PublicityCode;
private String GT1_39_ProtectionIndicator;
private String GT1_40_StudentIndicator;
private String GT1_41_Religion;
private String GT1_42_MothersMaidenName;
private String GT1_43_Nationality;
private String GT1_44_EthnicGroup;
private String GT1_45_ContactPersonsName;
private String GT1_46_ContactPersonsTelephoneNumber;
private String GT1_47_ContactReason;
private String GT1_48_ContactRelationship;
private String GT1_49_JobTitle;
private String GT1_50_JobCodeClass;
private String GT1_51_GuarantorEmployersOrganizationName;
private String GT1_52_Handicap;
private String GT1_53_JobStatus;
private String GT1_54_GuarantorFinancialClass;
private String GT1_55_GuarantorRace;
private String GT1_56_GuarantorBirthPlace;
private String GT1_57_VIPIndicator;
public String toString() { return ReflectionToStringBuilder.toString(this);}
}

